### Changes
- Updated this subproject to export simple function for GLSL fragment shader optimization.
- Modified the **CMakeLists.txt** to generate a **shared library** to access those functions (Currently for the use case of JNA).



#### Build instructions
- This project was built using **Visual Studio Code** with **CMake Tools** extension.
- The existing **CMakeLists.txt** should be sufficient.
- The build was successfully tested with the **VisualStudio.12.0 - amd64** kit (CMake).
- All relevent build outputs should be in **/build/Release/**

------------

### Original Readme
> 
This is a small sample program to get you quickly up and running, it transforms an input textfile to an output textfile. The input source textfile should be a fully preprocessed GLSL shader and the output should be a simple shader in textform.

> The project file is generated by BadgerConfig.

> VS2005
BadgerConfig

> Jim Tilander, Santa Monica 2010
